package net.demilich.metastone.game.cards.desc;

public enum ParseValueType {
    // Base parse value types
	BOOLEAN,
	INTEGER,
	STRING,
	STRING_ARRAY,

    // Attribute types
    MULTIPLIER,

    // Basic card desc types
	ATTRIBUTE,
	CARD_TYPE,
    CARD_TYPE_ARRAY,
	CONDITION,
	CONDITION_ARRAY,
	HERO_CLASS,
	HERO_CLASS_ARRAY,
	TRIBE,
	RARITY,
	SPELL,
	SPELL_ARRAY,
	TARGET_PLAYER,
	VALUE,
	VALUE_PROVIDER,

    // Advanced card desc types
	ENTITY_FILTER,
	ENTITY_FILTER_ARRAY,
	GROUP,
	TARGET_SELECTION,
	TARGET_REFERENCE,
	PLAYER_ATTRIBUTE,
	CARD_LOCATION,
	OPERATION,
	ALGEBRAIC_OPERATION,
	ENTITY_TYPE,
	ACTION_TYPE,
	TARGET_TYPE,
	TRIGGER,
	EVENT_TRIGGER,
	CARD_COST_MODIFIER,
	CARD_DESC_TYPE,
	CARD_SOURCE,
	GAME_VALUE,
}
